### ISSUE TITLE
opentype-font-prohibits-installable-embedding

### ISSUE THREAD

**Issue by alexmyczko** [froyotam/ferrite-core#2]
version 1.5 of your font shows me this warning when updating the debian font... is that a setting you can remove or is that intended?

**Comment by froyotam** [comment]
Strange, since I don't seem to have that issue on Font Book installing. For best results, be sure to uninstall previous versions before installing 1.5. Hope that works out.

Best,
Froyo

**Comment by alexmyczko** [comment]
I'm building the font myself with this command on Linux:

`fontmake -i -o otf -g sources/Ferrite-Core*.glyphs`

see https://github.com/googlefonts/fontmake
the Debian tool `lintian` reports the warning
